#!/bin/bash
#
# (c) Copyright codcodog
#
# PHP 语法检查以及代码规范检查
#
# 依赖：
# - composer
# - php-cs-fixer
# - php-parallel-lint
set -e

CODE_STYLE_CHECK='composer cc'
CODE_SYNTAX_CHECK='composer cl'

files=$(git diff --cached --name-only)

is_php()
{
  file_extension="${1##*.}"
  if [[ "$file_extension" == 'php' ]]; then
    return 0
  fi

  return 1
}

check_syntax()
{
  $CODE_SYNTAX_CHECK "$1"
  return $?
}

check_style()
{
  $CODE_STYLE_CHECK "$1"
  return $?
}

main()
{
  for f in $files; do
    if is_php "$f"; then
      if ! check_syntax "$f" > /dev/null 2>&1; then
        check_syntax "$f"
        exit 1
      fi
      if ! check_style "$f" > /dev/null 2>&1; then
        check_style "$f"
        exit 1
      fi
    fi
  done
}

main
exit 0
